name: Laravel CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Copy .env
      run: cp .env.example .env

    - name: List Docker containers and ports
      run: docker ps -a

    - name: Install Dependencies
      run: composer install --no-interaction --no-scripts --prefer-dist --ignore-platform-reqs

    - name: Install Node Dependencies
      run: npm install

    - name: Build Front-end Assets
      run: npm run build

    - name: Generate key
      run: php artisan key:generate

    - name: Run Sail
      run: ./vendor/bin/sail up -d

    - name: Wait for Sail to start
      run: sleep 30

    - name: Run Database Migrations
      run: ./vendor/bin/sail artisan migrate --force

    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: pgsql
        DB_HOST: localhost
        DB_PORT: 5432
        DB_DATABASE: laravel
        DB_USERNAME: postgres
        DB_PASSWORD: test
      run: ./vendor/bin/sail artisan test
