name: Laravel CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: laravel
          POSTGRES_PASSWORD: password
          POSTGRES_DB: laravel
        ports:
          - 5433:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v3

    - name: Copy .env
      run: cp .env.example .env

    - name: Install Dependencies
      run: composer install --no-interaction --no-scripts --prefer-dist --ignore-platform-reqs

    - name: Generate key
      run: php artisan key:generate

    - name: Run Sail
      run: ./vendor/bin/sail up -d

    - name: Wait for Sail to start
      run: sleep 30

    - name: Run Database Migrations
      run: ./vendor/bin/sail artisan migrate --force

    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: pgsql
        DB_HOST: localhost
        DB_PORT: 5432
        DB_DATABASE: laravel
        DB_USERNAME: postgres
        DB_PASSWORD: test
      run: ./vendor/bin/sail artisan test
